/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    AllOrders: typeof import('./src/components/AllOrders.vue')['default']
    Nearby: typeof import('./src/components/Nearby.vue')['default']
    Other: typeof import('./src/components/Other.vue')['default']
    PasswordLogin: typeof import('./src/components/PasswordLogin.vue')['default']
    Refund: typeof import('./src/components/Refund.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    Uncomment: typeof import('./src/components/Uncomment.vue')['default']
    Unpaid: typeof import('./src/components/Unpaid.vue')['default']
    VanButton: typeof import('vant/es')['Button']
    VanCard: typeof import('vant/es')['Card']
    VanCell: typeof import('vant/es')['Cell']
    VanCellGroup: typeof import('vant/es')['CellGroup']
    VanCheckbox: typeof import('vant/es')['Checkbox']
    VanCheckboxGroup: typeof import('vant/es')['CheckboxGroup']
    VanCol: typeof import('vant/es')['Col']
    VanDropdownItem: typeof import('vant/es')['DropdownItem']
    VanDropdownMenu: typeof import('vant/es')['DropdownMenu']
    VanEmpty: typeof import('vant/es')['Empty']
    VanImage: typeof import('vant/es')['Image']
    VanLoading: typeof import('vant/es')['Loading']
    VanRow: typeof import('vant/es')['Row']
    VanSkeleton: typeof import('vant/es')['Skeleton']
    VanStepper: typeof import('vant/es')['Stepper']
    VanTab: typeof import('vant/es')['Tab']
    VanTabs: typeof import('vant/es')['Tabs']
    VanTag: typeof import('vant/es')['Tag']
  }
}
